### ISSUE TITLE
`/api/changes/entity/<schema_slug>/<unknown_entity_slug>` replies with status 500

### ISSUE THREAD

**Issue by crazyscientist** [SUSE/aimaas#128]
# Steps to reproduce

1. Create a schema with arbitrary slug.
1. Create an entity with an arbitrary slug. (Or don't :stuck_out_tongue_closed_eyes: )
2. Run a HTTP GET query with the valid slug of the schema and an invalid/non-existing entity slug

The HTTP request triggered by the last action will return `500 Internal Server Error`

# Example

```
$ http http://localhost:8080/api/changes/entity/foo/does-not-exist
HTTP/1.1 500 Internal Server Error
Vary: Accept-Encoding
X-Powered-By: Express
connection: close
content-length: 21
content-type: text/plain; charset=utf-8
date: Tue, 04 Apr 2023 13:59:11 GMT
server: uvicorn

Internal Server Error
```
In this example, `foo` is the slug of my schema, but there is no entity with the slug `does-not-exist`.

# Traceback
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/andi/virtualenvs/aimaas/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/andi/workspace/aimaas/./backend/general_routes.py", line 237, in get_entity_changes
    return get_recent_entity_changes(db=db, entity_id=entity.id, params=params)
AttributeError: 'NoneType' object has no attribute 'id'
```

# Expected behavior

The API should reply with HTTP 404 Not Found.

**Comment by esskayesss** [comment]
could this be because in the following line:
https://github.com/SUSE/aimaas/blob/f7bf8cebc5ad36aa773d46024b46522fd014742d/backend/general_routes.py#L237

the `get_entity()` method should've been called instead?
https://github.com/SUSE/aimaas/blob/f7bf8cebc5ad36aa773d46024b46522fd014742d/backend/crud.py#L544-L551


if i'm right, i would like to push the fix to this issue.

**Comment by crazyscientist** [comment]
@esskayesss Thank you for picking up this issue.

I see your point, `get_entity()` would raise a `MissingEntityException` for us.

On the other hand, if the entity exists, the function would fetch all the attributes from the database, but only the entity ID will be used. `get_recent_entity_changes()` will fetch those again in order to create a dataset to represent the changes.

I checked, where `get_entity_model` is used, and I'm wondering, whether it would be better to move lines 547-548 (the `if` and `raise` statements) from `get_entity` into `get_entity_model`.

**Comment by esskayesss** [comment]
the original `get_entity_model` would also have caused an error at line 487
https://github.com/SUSE/aimaas/blob/d88100461764cc59634839d63c35aa5801a2b111/backend/traceability/entity.py#L481-L487
