### ISSUE TITLE
Attributes with invalid name can be added to schema

### ISSUE THREAD

**Issue by crazyscientist** [SUSE/aimaas#37]
During development I came across this case:

### How to reproduce?

1.  Update an existing schema by adding an attribute with an _invalid_ name (e.g. `"403"`).
2. Schema gets changed, but request gets a 500 reply (traceback see below).
3. Schema definition contains the new attribute, but the validation model in the backend does not.
4. One cannot update entities via the UI. All attempts get a 422 response.

### Traceback
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/andi/virtualenvs/aimaas/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/andi/workspace/aimaas/./backend/general_routes.py", line 109, in update_schema
    create_dynamic_router(schema=schema, old_slug=old_slug, app=request.app, get_db=get_db)
  File "/home/andi/workspace/aimaas/./backend/dynamic_routes.py", line 397, in create_dynamic_router
    route_get_entities(router=router, schema=schema, get_db=get_db)
  File "/home/andi/workspace/aimaas/./backend/dynamic_routes.py", line 162, in route_get_entities
    filter_model = _filters_request_model(schema=schema)
  File "/home/andi/workspace/aimaas/./backend/dynamic_routes.py", line 155, in _filters_request_model
    filter_model = make_dataclass(f"{schema.slug.capitalize().replace('-', '_')}Filters", fields=fields)
  File "/usr/lib/python3.9/dataclasses.py", line 1219, in make_dataclass
    raise TypeError(f'Field names must be valid identifiers: {name!r}')
TypeError: Field names must be valid identifiers: '403'
```

### Expected behavior

* Invalid identifiers are not accepted during CREATE and UPDATE queries.
* The response code is 422.

**Comment by crazyscientist** [comment]
FYI, the presence of such an _invalid_ attribute also prevents the server from starting.
